### ISSUE TITLE
✍📜 LICENSE - Automation & Existence 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/nvvs-devops#178]
### User Story

As a… Cloud Ops Administrator 
I expect... LICENSE files to exist and PRs to be raised (akin to dependabot) when a LICENSE file does not exist
So that… we know we have uniform license file setup across our repositories. 

### Value / Purpose

At the moment this is an option when creating a repository. This is fine, however different admins may or may not create the LICENSE file and repositories may become non-uniform.

### Useful Contacts

Gary Henderson, Aaron Robinson

### Additional Information

First thoughts are we can use Renovate or GitHub Actions to do this. 

### Definition of Done

- [ ] All of our repositories have a license
- [ ] All repositories are automatically monitored

**Comment by Gary-H9** [comment]
I've iterated on this locally and now the script looks like the following code, I've removed the `andstor` module for something more _timeless_. 
```
name: "MIT License Check"

on: [push, pull_request]

jobs:
  existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        run: test -f LICENSE && echo "LICENSE exists."
  
  contents:
    needs: existence
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Read LICENSE file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: LICENSE
      
      - name: LICENSE Contents
        run: echo "${{ steps.package.outputs.content }}"

  sha1sum:
    needs: existence
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: sha1sum LICENSE
        run: sha1sum LICENSE

      - name: Check contents of LICENSE using sha1sum
        run: sha1sum -c .github/workflows/LICENSE.sha1
    
  year:
    needs: existence
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v1

      - name: License Year
        run: cat LICENSE | awk '{ print $3 }' | awk 'FNR==3 {print}'
```

I'd like to test to see if the year is correct and then latterly that the 'Ministry of Justice' organisation string is mentioned in line 3 of the LICENSE file.
